version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    container_name: waiting-list-test-db
    environment:
      - POSTGRES_DB=survey_system_test
      - POSTGRES_USER=hamza
      - POSTGRES_PASSWORD=hamza
    ports:
      - "5434:5432"  # Different port to avoid conflicts
    networks:
      - waiting-list-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hamza -d survey_system_test"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  waiting-list-test-network:
    driver: bridge